# Generated by Django 5.1.7 on 2025-04-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('request_count', models.IntegerField(default=1)),
                ('last_request', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Address',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Certificate setting',
                'verbose_name_plural': 'Certificate settings',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=5)),
                ('length', models.IntegerField()),
                ('mask', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_checked', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('language_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='Contact.certificate', verbose_name='Til sertifikati')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
            },
        ),
        migrations.CreateModel(
            name='CheckedContact',
            fields=[
            ],
            options={
                'verbose_name': 'Tekshirilgan Kontakt',
                'verbose_name_plural': 'Tekshitilgan Kontaklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Contact.contact',),
        ),
        migrations.CreateModel(
            name='UncheckedContact',
            fields=[
            ],
            options={
                'verbose_name': 'Tekshirilmagan Kontakt',
                'verbose_name_plural': 'Tekshirilmagan Kontaklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Contact.contact',),
        ),
    ]
