# Generated by Django 5.1.6 on 2025-04-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_succdesc_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallNum',
        ),
        migrations.DeleteModel(
            name='IndexTitle',
        ),
        migrations.DeleteModel(
            name='MaxImage',
        ),
        migrations.DeleteModel(
            name='MinImage',
        ),
        migrations.DeleteModel(
            name='SuccDesc',
        ),
        migrations.DeleteModel(
            name='SuccDocPic',
        ),
        migrations.DeleteModel(
            name='SuccLink',
        ),
        migrations.DeleteModel(
            name='SuccText',
        ),
    ]
