# Generated by Django 5.2.3 on 2025-06-30 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('terrace', 'Terrace'), ('panorama', 'Panorama')], default='standard', max_length=20)),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00')], max_length=5)),
                ('people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tables', models.ManyToManyField(related_name='reservations', to='backend.table')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'created_at'], name='backend_res_phone_e23923_idx')],
            },
        ),
    ]
