# Generated by Django 5.1.7 on 2025-03-28 02:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_whychoose_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortinfo',
            old_name='color',
            new_name='bgColor',
        ),
        migrations.AddField(
            model_name='shortinfo',
            name='fontColor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
