# Generated by Django 5.1.7 on 2025-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_color_shortinfo_bgcolor_shortinfo_fontcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='details_url',
            field=models.URLField(),
        ),
    ]
