# Generated by Django 5.1.7 on 2025-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_university_details_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='details_url',
            field=models.URLField(unique=True),
        ),
    ]
