# Generated by Django 5.1.7 on 2025-04-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_blockedip_certificate_certificatesetting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedIP',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='language_certificate',
        ),
        migrations.DeleteModel(
            name='CertificateSetting',
        ),
        migrations.DeleteModel(
            name='ContactCountry',
        ),
        migrations.DeleteModel(
            name='CheckedContact',
        ),
        migrations.DeleteModel(
            name='UncheckedContact',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
