# Generated by Django 5.1.7 on 2025-04-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_delete_blockedip_remove_contact_language_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='programmes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='requirements',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarships',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('context', models.CharField(max_length=1000)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_set', to='backend.university')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('context', models.CharField(max_length=1000)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_set', to='backend.university')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('context', models.CharField(max_length=1000)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_set', to='backend.university')),
            ],
        ),
    ]
