# Generated by Django 5.1.7 on 2025-04-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_requirements_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmes',
            name='context',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='context',
        ),
        migrations.CreateModel(
            name='ProgrammesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
                ('programmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmesdata_set', to='backend.programmes')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
                ('programmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirementsdata_set', to='backend.requirements')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
                ('programmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmesdata_set', to='backend.scholarships')),
            ],
        ),
    ]
