# Generated by Django 5.1.7 on 2025-04-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_programmes_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='context',
        ),
    ]
